services:
  nginx:
    container_name: nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/docker/data/nginx/acme.sh:/root/.acme.sh
      - /var/docker/data/nginx/ssl:/etc/nginx/ssl
      - /var/docker/data/nginx/conf.d:/etc/nginx/conf.d
      - /var/docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - CF_Token=${CF_Token}
      - DOMAIN=${DOMAIN}